# Generated by Django 4.2.13 on 2024-06-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("published_date", models.DateField()),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
    ]
